CREATE TABLE `betaInvites` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`inviteCode` varchar(20) NOT NULL,
	`email` varchar(255),
	`mechanicName` varchar(100),
	`mechanicShop` varchar(100),
	`invitedBy` varchar(100),
	`status` enum('pending','accepted','expired','revoked') DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`acceptedAt` timestamp,
	`expiresAt` timestamp,
	CONSTRAINT `betaInvites_id` PRIMARY KEY(`id`),
	CONSTRAINT `betaInvites_inviteCode_unique` UNIQUE(`inviteCode`)
);
--> statement-breakpoint
CREATE TABLE `betaUsers` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`userId` varchar(100) NOT NULL,
	`mechanicName` varchar(100),
	`mechanicShop` varchar(100),
	`email` varchar(255),
	`phone` varchar(20),
	`specialties` json,
	`certifications` json,
	`experienceYears` int,
	`diagnosticsCount` int DEFAULT 0,
	`feedbackCount` int DEFAULT 0,
	`avgRating` decimal(3,2),
	`status` enum('active','inactive','suspended') DEFAULT 'active',
	`joinedAt` timestamp NOT NULL DEFAULT (now()),
	`lastActive` timestamp,
	CONSTRAINT `betaUsers_id` PRIMARY KEY(`id`),
	CONSTRAINT `betaUsers_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `repairCases` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`vehicleMake` varchar(50) NOT NULL,
	`vehicleModel` varchar(100) NOT NULL,
	`vehicleYear` int,
	`engine` varchar(100),
	`engineCode` varchar(50),
	`errorCode` varchar(20),
	`errorSystem` varchar(50),
	`errorDescription` text,
	`symptoms` json,
	`repairAction` varchar(255),
	`repairPerformed` text,
	`repairTimeHours` decimal(5,2),
	`repairCostEstimate` decimal(10,2),
	`repairCostActual` decimal(10,2),
	`toolsUsed` json,
	`partsNeeded` json,
	`repairOutcome` enum('success','partial','failed','unknown') DEFAULT 'unknown',
	`confidence` decimal(3,2),
	`sourceUrl` varchar(500),
	`sourceDomain` varchar(100),
	`sourceType` enum('forum','reddit','manual','obd','blog','video') DEFAULT 'forum',
	`evidenceSnippets` json,
	`evidenceQuality` decimal(3,2),
	`language` varchar(10) DEFAULT 'en',
	`canonicalKey` varchar(255),
	`clusterId` varchar(100),
	`mergedCount` int DEFAULT 1,
	`sourceCount` int DEFAULT 1,
	`rawJson` text,
	`contentHash` varchar(64),
	`normalizedHash` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `repairCases_id` PRIMARY KEY(`id`),
	CONSTRAINT `repairCases_canonicalKey_unique` UNIQUE(`canonicalKey`)
);
--> statement-breakpoint
CREATE TABLE `repairFeedback` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`diagnosticId` varchar(100),
	`userId` varchar(100),
	`mechanicId` varchar(100),
	`vehicleMake` varchar(50),
	`vehicleModel` varchar(100),
	`vehicleYear` int,
	`engine` varchar(100),
	`engineCode` varchar(50),
	`errorCode` varchar(20),
	`repairAction` varchar(255),
	`success` enum('true','false','partial'),
	`repairTimeHours` decimal(5,2),
	`repairCost` decimal(10,2),
	`actualCost` decimal(10,2),
	`costVariance` decimal(10,2),
	`feedbackText` text,
	`rating` int,
	`issuesFound` json,
	`improvementsSuggested` json,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `repairFeedback_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `repairOutcomes` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`vehicleMake` varchar(50) NOT NULL,
	`vehicleModel` varchar(100) NOT NULL,
	`vehicleYear` int,
	`engine` varchar(100),
	`engineCode` varchar(50),
	`errorCode` varchar(20) NOT NULL,
	`errorSystem` varchar(50),
	`repairAction` varchar(255) NOT NULL,
	`success` enum('true','false','unknown'),
	`repairTimeHours` decimal(5,2),
	`repairCost` decimal(10,2),
	`sourceDomain` varchar(100),
	`sourceUrl` varchar(500),
	`confidence` decimal(3,2),
	`successRate` decimal(5,2),
	`totalCases` int DEFAULT 1,
	`avgRepairTime` decimal(5,2),
	`avgRepairCost` decimal(10,2),
	`successCount` int DEFAULT 0,
	`failureCount` int DEFAULT 0,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `repairOutcomes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `serviceProcedures` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`vehicleMake` varchar(50) NOT NULL,
	`vehicleModel` varchar(100) NOT NULL,
	`vehicleYear` int,
	`engine` varchar(100),
	`engineCode` varchar(50),
	`systemType` varchar(100),
	`procedureName` varchar(255) NOT NULL,
	`procedureDescription` text,
	`repairSteps` json NOT NULL,
	`toolsRequired` json,
	`torqueSpecs` json,
	`estimatedTimeHours` decimal(5,2),
	`difficultyLevel` enum('easy','medium','hard','expert') DEFAULT 'medium',
	`confidence` decimal(3,2),
	`sourceUrl` varchar(500),
	`sourceDomain` varchar(100),
	`sourceType` enum('manual','forum','blog','video') DEFAULT 'manual',
	`evidenceSnippets` json,
	`evidenceQuality` decimal(3,2),
	`language` varchar(10) DEFAULT 'en',
	`canonicalKey` varchar(255),
	`rawJson` text,
	`contentHash` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `serviceProcedures_id` PRIMARY KEY(`id`),
	CONSTRAINT `serviceProcedures_canonicalKey_unique` UNIQUE(`canonicalKey`)
);
--> statement-breakpoint
CREATE TABLE `sourceRegistry` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`sourceUrl` varchar(500) NOT NULL,
	`sourceDomain` varchar(100) NOT NULL,
	`sourceType` enum('forum','reddit','manual','obd','blog','video','other') DEFAULT 'forum',
	`sourceCategory` varchar(100),
	`sourceName` varchar(255),
	`accessibilityScore` decimal(3,2),
	`relevanceScore` decimal(3,2),
	`qualityScore` decimal(3,2),
	`extractionScore` decimal(3,2),
	`legalRiskScore` decimal(3,2),
	`overallScore` decimal(3,2),
	`pagesScanned` int DEFAULT 0,
	`uniqueRecords` int DEFAULT 0,
	`duplicateRate` decimal(5,2) DEFAULT '0',
	`avgConfidence` decimal(3,2),
	`yieldScore` decimal(5,2),
	`lastScanned` timestamp,
	`cooldownUntil` timestamp,
	`blacklisted` boolean DEFAULT false,
	`blacklistReason` varchar(255),
	`discoveredFrom` varchar(255),
	`discoveryQuery` varchar(255),
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sourceRegistry_id` PRIMARY KEY(`id`),
	CONSTRAINT `sourceRegistry_sourceUrl_unique` UNIQUE(`sourceUrl`)
);
--> statement-breakpoint
CREATE TABLE `torqueSpecifications` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`vehicleMake` varchar(50) NOT NULL,
	`vehicleModel` varchar(100) NOT NULL,
	`vehicleYear` int,
	`engine` varchar(100),
	`engineCode` varchar(50),
	`systemType` varchar(100),
	`componentName` varchar(255) NOT NULL,
	`torqueValueNm` decimal(8,2) NOT NULL,
	`torqueValueFtlb` decimal(8,2),
	`torqueSequence` varchar(255),
	`torquePattern` varchar(255),
	`coldTorque` decimal(8,2),
	`warmTorque` decimal(8,2),
	`notes` text,
	`confidence` decimal(3,2),
	`sourceUrl` varchar(500),
	`sourceDomain` varchar(100),
	`evidenceSnippet` text,
	`evidenceQuality` decimal(3,2),
	`language` varchar(10) DEFAULT 'en',
	`canonicalKey` varchar(255),
	`rawJson` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `torqueSpecifications_id` PRIMARY KEY(`id`),
	CONSTRAINT `torqueSpecifications_canonicalKey_unique` UNIQUE(`canonicalKey`)
);
