// Professional Autodata-style vehicle specifications database
export const vehicleSpecifications = {
  "Volkswagen": {
    "Phaeton": [
      {
        id: "vw-phaeton-3.0-tdi-lwb",
        model: "Phaeton",
        year: "2010-2018",
        engine: "3.0 TDI",
        engineType: "Diesel",
        power: "171 kW (233 PS)",
        torque: "500 Nm",
        transmission: "Automatic 8-speed",
        bodyStyle: "Sedan",
        length: "LWB (Long Wheelbase)",
        seats: 5,
        fuelConsumption: "7.8 L/100km",
        co2: "205 g/km",
        acceleration: "7.8 s (0-100 km/h)",
        topSpeed: "230 km/h",
        tankCapacity: "75 L",
        driveType: "AWD (4Motion)",
      },
      {
        id: "vw-phaeton-4.2-benzin-lwb",
        model: "Phaeton",
        year: "2002-2016",
        engine: "4.2 FSI",
        engineType: "Petrol",
        power: "309 kW (420 PS)",
        torque: "450 Nm",
        transmission: "Automatic 6-speed",
        bodyStyle: "Sedan",
        length: "LWB (Long Wheelbase)",
        seats: 5,
        fuelConsumption: "11.5 L/100km",
        co2: "270 g/km",
        acceleration: "6.0 s (0-100 km/h)",
        topSpeed: "250 km/h",
        tankCapacity: "75 L",
        driveType: "AWD (4Motion)",
      },
      {
        id: "vw-phaeton-3.0-v6-swb",
        model: "Phaeton",
        year: "2002-2016",
        engine: "3.0 V6",
        engineType: "Petrol",
        power: "177 kW (240 PS)",
        torque: "310 Nm",
        transmission: "Automatic 6-speed",
        bodyStyle: "Sedan",
        length: "SWB (Standard Wheelbase)",
        seats: 4,
        fuelConsumption: "10.2 L/100km",
        co2: "240 g/km",
        acceleration: "8.5 s (0-100 km/h)",
        topSpeed: "220 km/h",
        tankCapacity: "75 L",
        driveType: "FWD",
      },
      {
        id: "vw-phaeton-5.0-v10-tdi",
        model: "Phaeton",
        year: "2004-2016",
        engine: "5.0 V10 TDI",
        engineType: "Diesel",
        power: "313 kW (425 PS)",
        torque: "900 Nm",
        transmission: "Automatic 6-speed",
        bodyStyle: "Sedan",
        length: "LWB (Long Wheelbase)",
        seats: 5,
        fuelConsumption: "9.5 L/100km",
        co2: "250 g/km",
        acceleration: "5.5 s (0-100 km/h)",
        topSpeed: "250 km/h",
        tankCapacity: "75 L",
        driveType: "AWD (4Motion)",
      },
    ],
    "Golf": [
      {
        id: "vw-golf-1.6-tdi",
        model: "Golf",
        year: "2009-2021",
        engine: "1.6 TDI",
        engineType: "Diesel",
        power: "77 kW (105 PS)",
        torque: "250 Nm",
        transmission: "Manual 5-speed",
        bodyStyle: "Hatchback",
        length: "Standard",
        seats: 5,
        fuelConsumption: "4.5 L/100km",
        co2: "119 g/km",
        acceleration: "10.2 s (0-100 km/h)",
        topSpeed: "190 km/h",
        tankCapacity: "50 L",
        driveType: "FWD",
      },
      {
        id: "vw-golf-2.0-tsi-gti",
        model: "Golf GTI",
        year: "2009-2021",
        engine: "2.0 TSI",
        engineType: "Petrol",
        power: "169 kW (230 PS)",
        torque: "320 Nm",
        transmission: "Manual 6-speed",
        bodyStyle: "Hatchback",
        length: "Standard",
        seats: 5,
        fuelConsumption: "7.2 L/100km",
        co2: "165 g/km",
        acceleration: "6.2 s (0-100 km/h)",
        topSpeed: "237 km/h",
        tankCapacity: "50 L",
        driveType: "FWD",
      },
    ],
    "Passat": [
      {
        id: "vw-passat-2.0-tdi-sedan",
        model: "Passat",
        year: "2010-2020",
        engine: "2.0 TDI",
        engineType: "Diesel",
        power: "110 kW (150 PS)",
        torque: "340 Nm",
        transmission: "Manual 6-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "5.2 L/100km",
        co2: "136 g/km",
        acceleration: "9.3 s (0-100 km/h)",
        topSpeed: "210 km/h",
        tankCapacity: "70 L",
        driveType: "FWD",
      },
      {
        id: "vw-passat-1.8-tsi-combi",
        model: "Passat Combi",
        year: "2010-2020",
        engine: "1.8 TSI",
        engineType: "Petrol",
        power: "118 kW (160 PS)",
        torque: "250 Nm",
        transmission: "Automatic 7-speed DSG",
        bodyStyle: "Estate",
        length: "Standard",
        seats: 5,
        fuelConsumption: "6.8 L/100km",
        co2: "158 g/km",
        acceleration: "8.4 s (0-100 km/h)",
        topSpeed: "215 km/h",
        tankCapacity: "70 L",
        driveType: "FWD",
      },
    ],
  },
  "Audi": {
    "A4": [
      {
        id: "audi-a4-2.0-tdi-sedan",
        model: "A4",
        year: "2008-2020",
        engine: "2.0 TDI",
        engineType: "Diesel",
        power: "120 kW (163 PS)",
        torque: "380 Nm",
        transmission: "Manual 6-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "5.4 L/100km",
        co2: "142 g/km",
        acceleration: "8.9 s (0-100 km/h)",
        topSpeed: "215 km/h",
        tankCapacity: "63 L",
        driveType: "FWD",
      },
      {
        id: "audi-a4-3.0-tdi-quattro",
        model: "A4",
        year: "2008-2020",
        engine: "3.0 TDI",
        engineType: "Diesel",
        power: "176 kW (240 PS)",
        torque: "500 Nm",
        transmission: "Automatic 8-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "6.2 L/100km",
        co2: "162 g/km",
        acceleration: "6.1 s (0-100 km/h)",
        topSpeed: "230 km/h",
        tankCapacity: "63 L",
        driveType: "AWD (Quattro)",
      },
    ],
    "A6": [
      {
        id: "audi-a6-2.0-tfsi-sedan",
        model: "A6",
        year: "2011-2018",
        engine: "2.0 TFSI",
        engineType: "Petrol",
        power: "180 kW (245 PS)",
        torque: "370 Nm",
        transmission: "Automatic 8-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "7.5 L/100km",
        co2: "175 g/km",
        acceleration: "7.1 s (0-100 km/h)",
        topSpeed: "235 km/h",
        tankCapacity: "75 L",
        driveType: "FWD",
      },
    ],
  },
  "BMW": {
    "320i": [
      {
        id: "bmw-320i-2.0-petrol",
        model: "320i",
        year: "2012-2019",
        engine: "2.0 TwinPower Turbo",
        engineType: "Petrol",
        power: "135 kW (184 PS)",
        torque: "300 Nm",
        transmission: "Automatic 8-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "7.2 L/100km",
        co2: "169 g/km",
        acceleration: "8.1 s (0-100 km/h)",
        topSpeed: "225 km/h",
        tankCapacity: "60 L",
        driveType: "RWD",
      },
    ],
    "330d": [
      {
        id: "bmw-330d-3.0-diesel",
        model: "330d",
        year: "2012-2019",
        engine: "3.0 TwinPower Turbo",
        engineType: "Diesel",
        power: "190 kW (258 PS)",
        torque: "560 Nm",
        transmission: "Automatic 8-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "6.1 L/100km",
        co2: "160 g/km",
        acceleration: "5.8 s (0-100 km/h)",
        topSpeed: "245 km/h",
        tankCapacity: "60 L",
        driveType: "RWD",
      },
    ],
  },
  "Mercedes-Benz": {
    "C-Class": [
      {
        id: "merc-c200-2.0-petrol",
        model: "C200",
        year: "2014-2021",
        engine: "2.0 Turbo",
        engineType: "Petrol",
        power: "135 kW (184 PS)",
        torque: "300 Nm",
        transmission: "Automatic 9-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "7.4 L/100km",
        co2: "170 g/km",
        acceleration: "8.6 s (0-100 km/h)",
        topSpeed: "230 km/h",
        tankCapacity: "66 L",
        driveType: "RWD",
      },
      {
        id: "merc-c220-2.0-diesel",
        model: "C220",
        year: "2014-2021",
        engine: "2.0 Turbo Diesel",
        engineType: "Diesel",
        power: "125 kW (170 PS)",
        torque: "400 Nm",
        transmission: "Automatic 9-speed",
        bodyStyle: "Sedan",
        length: "Standard",
        seats: 5,
        fuelConsumption: "5.6 L/100km",
        co2: "147 g/km",
        acceleration: "9.2 s (0-100 km/h)",
        topSpeed: "225 km/h",
        tankCapacity: "66 L",
        driveType: "RWD",
      },
    ],
  },
};

export type VehicleSpec = typeof vehicleSpecifications[keyof typeof vehicleSpecifications][keyof typeof vehicleSpecifications[keyof typeof vehicleSpecifications]][0];
